/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PeerMentorship } from "./PeerMentorship";
export * as factories from "./factories";
export { PeerMentorship__factory } from "./factories/PeerMentorship__factory";
