/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace PeerMentorship {
  export type ProposalStruct = {
    id: BigNumberish;
    description: string;
    forVotes: BigNumberish;
    againstVotes: BigNumberish;
    endTime: BigNumberish;
    executed: boolean;
    exists: boolean;
  };

  export type ProposalStructOutput = [
    id: bigint,
    description: string,
    forVotes: bigint,
    againstVotes: bigint,
    endTime: bigint,
    executed: boolean,
    exists: boolean
  ] & {
    id: bigint;
    description: string;
    forVotes: bigint;
    againstVotes: bigint;
    endTime: bigint;
    executed: boolean;
    exists: boolean;
  };

  export type SessionStruct = {
    id: BigNumberish;
    mentor: AddressLike;
    mentee: AddressLike;
    topic: string;
    duration: BigNumberish;
    timestamp: BigNumberish;
    verified: boolean;
    exists: boolean;
  };

  export type SessionStructOutput = [
    id: bigint,
    mentor: string,
    mentee: string,
    topic: string,
    duration: bigint,
    timestamp: bigint,
    verified: boolean,
    exists: boolean
  ] & {
    id: bigint;
    mentor: string;
    mentee: string;
    topic: string;
    duration: bigint;
    timestamp: bigint;
    verified: boolean;
    exists: boolean;
  };

  export type UserStruct = {
    role: BigNumberish;
    contributionPoints: BigNumberish;
    sessionsCompleted: BigNumberish;
    sessionsVerified: BigNumberish;
    registered: boolean;
  };

  export type UserStructOutput = [
    role: bigint,
    contributionPoints: bigint,
    sessionsCompleted: bigint,
    sessionsVerified: bigint,
    registered: boolean
  ] & {
    role: bigint;
    contributionPoints: bigint;
    sessionsCompleted: bigint;
    sessionsVerified: bigint;
    registered: boolean;
  };
}

export interface PeerMentorshipInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_POINTS_TO_VOTE"
      | "POINTS_PER_SESSION"
      | "VERIFICATION_BONUS"
      | "VOTING_PERIOD"
      | "admin"
      | "createProposal"
      | "getBadgeInfo"
      | "getProposal"
      | "getSession"
      | "getTopMentors"
      | "getUser"
      | "getUserSessions"
      | "getUserVoted"
      | "hasBadge"
      | "hasVoted"
      | "hasVotingRights"
      | "logSession"
      | "proposalCount"
      | "proposals"
      | "register"
      | "resetUserPoints"
      | "sessionCount"
      | "sessions"
      | "userBadges"
      | "users"
      | "verifySession"
      | "vote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BadgeAwarded"
      | "PointsUpdated"
      | "ProposalCreated"
      | "SessionLogged"
      | "SessionVerified"
      | "UserRegistered"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MIN_POINTS_TO_VOTE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "POINTS_PER_SESSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFICATION_BONUS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VOTING_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBadgeInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSession",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTopMentors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSessions",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserVoted",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasBadge",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVotingRights",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logSession",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resetUserPoints",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sessionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sessions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userBadges",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "users", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "verifySession",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "MIN_POINTS_TO_VOTE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "POINTS_PER_SESSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFICATION_BONUS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VOTING_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBadgeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSession", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTopMentors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserSessions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserVoted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasBadge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasVotingRights",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "logSession", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resetUserPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sessionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sessions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userBadges", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifySession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
}

export namespace BadgeAwardedEvent {
  export type InputTuple = [user: AddressLike, badgeId: BigNumberish];
  export type OutputTuple = [user: string, badgeId: bigint];
  export interface OutputObject {
    user: string;
    badgeId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PointsUpdatedEvent {
  export type InputTuple = [user: AddressLike, newPoints: BigNumberish];
  export type OutputTuple = [user: string, newPoints: bigint];
  export interface OutputObject {
    user: string;
    newPoints: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    creator: AddressLike,
    description: string
  ];
  export type OutputTuple = [
    proposalId: bigint,
    creator: string,
    description: string
  ];
  export interface OutputObject {
    proposalId: bigint;
    creator: string;
    description: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionLoggedEvent {
  export type InputTuple = [
    sessionId: BigNumberish,
    mentor: AddressLike,
    mentee: AddressLike,
    topic: string
  ];
  export type OutputTuple = [
    sessionId: bigint,
    mentor: string,
    mentee: string,
    topic: string
  ];
  export interface OutputObject {
    sessionId: bigint;
    mentor: string;
    mentee: string;
    topic: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionVerifiedEvent {
  export type InputTuple = [sessionId: BigNumberish, verifier: AddressLike];
  export type OutputTuple = [sessionId: bigint, verifier: string];
  export interface OutputObject {
    sessionId: bigint;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [user: AddressLike, role: BigNumberish];
  export type OutputTuple = [user: string, role: bigint];
  export interface OutputObject {
    user: string;
    role: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    voter: AddressLike,
    support: boolean,
    votingPower: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    voter: string,
    support: boolean,
    votingPower: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    voter: string;
    support: boolean;
    votingPower: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PeerMentorship extends BaseContract {
  connect(runner?: ContractRunner | null): PeerMentorship;
  waitForDeployment(): Promise<this>;

  interface: PeerMentorshipInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_POINTS_TO_VOTE: TypedContractMethod<[], [bigint], "view">;

  POINTS_PER_SESSION: TypedContractMethod<[], [bigint], "view">;

  VERIFICATION_BONUS: TypedContractMethod<[], [bigint], "view">;

  VOTING_PERIOD: TypedContractMethod<[], [bigint], "view">;

  admin: TypedContractMethod<[], [string], "view">;

  createProposal: TypedContractMethod<
    [_description: string],
    [bigint],
    "nonpayable"
  >;

  getBadgeInfo: TypedContractMethod<
    [_badgeId: BigNumberish],
    [
      [string, string, bigint] & {
        name: string;
        description: string;
        pointsRequired: bigint;
      }
    ],
    "view"
  >;

  getProposal: TypedContractMethod<
    [_proposalId: BigNumberish],
    [PeerMentorship.ProposalStructOutput],
    "view"
  >;

  getSession: TypedContractMethod<
    [_sessionId: BigNumberish],
    [PeerMentorship.SessionStructOutput],
    "view"
  >;

  getTopMentors: TypedContractMethod<
    [_limit: BigNumberish],
    [[string[], bigint[]]],
    "view"
  >;

  getUser: TypedContractMethod<
    [_userAddress: AddressLike],
    [PeerMentorship.UserStructOutput],
    "view"
  >;

  getUserSessions: TypedContractMethod<
    [_user: AddressLike, _asMentor: boolean],
    [PeerMentorship.SessionStructOutput[]],
    "view"
  >;

  getUserVoted: TypedContractMethod<
    [_user: AddressLike, _proposalId: BigNumberish],
    [boolean],
    "view"
  >;

  hasBadge: TypedContractMethod<
    [_user: AddressLike, _badgeId: BigNumberish],
    [boolean],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  hasVotingRights: TypedContractMethod<
    [_userAddress: AddressLike],
    [boolean],
    "view"
  >;

  logSession: TypedContractMethod<
    [_mentee: AddressLike, _topic: string, _duration: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  proposalCount: TypedContractMethod<[], [bigint], "view">;

  proposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, boolean, boolean] & {
        id: bigint;
        description: string;
        forVotes: bigint;
        againstVotes: bigint;
        endTime: bigint;
        executed: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;

  register: TypedContractMethod<[_role: BigNumberish], [void], "nonpayable">;

  resetUserPoints: TypedContractMethod<
    [_user: AddressLike],
    [void],
    "nonpayable"
  >;

  sessionCount: TypedContractMethod<[], [bigint], "view">;

  sessions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean, boolean] & {
        id: bigint;
        mentor: string;
        mentee: string;
        topic: string;
        duration: bigint;
        timestamp: bigint;
        verified: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;

  userBadges: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  users: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        role: bigint;
        contributionPoints: bigint;
        sessionsCompleted: bigint;
        sessionsVerified: bigint;
        registered: boolean;
      }
    ],
    "view"
  >;

  verifySession: TypedContractMethod<
    [_sessionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  vote: TypedContractMethod<
    [_proposalId: BigNumberish, _support: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_POINTS_TO_VOTE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "POINTS_PER_SESSION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERIFICATION_BONUS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VOTING_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createProposal"
  ): TypedContractMethod<[_description: string], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getBadgeInfo"
  ): TypedContractMethod<
    [_badgeId: BigNumberish],
    [
      [string, string, bigint] & {
        name: string;
        description: string;
        pointsRequired: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [_proposalId: BigNumberish],
    [PeerMentorship.ProposalStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSession"
  ): TypedContractMethod<
    [_sessionId: BigNumberish],
    [PeerMentorship.SessionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTopMentors"
  ): TypedContractMethod<
    [_limit: BigNumberish],
    [[string[], bigint[]]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUser"
  ): TypedContractMethod<
    [_userAddress: AddressLike],
    [PeerMentorship.UserStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserSessions"
  ): TypedContractMethod<
    [_user: AddressLike, _asMentor: boolean],
    [PeerMentorship.SessionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserVoted"
  ): TypedContractMethod<
    [_user: AddressLike, _proposalId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasBadge"
  ): TypedContractMethod<
    [_user: AddressLike, _badgeId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVotingRights"
  ): TypedContractMethod<[_userAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "logSession"
  ): TypedContractMethod<
    [_mentee: AddressLike, _topic: string, _duration: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proposalCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, boolean, boolean] & {
        id: bigint;
        description: string;
        forVotes: bigint;
        againstVotes: bigint;
        endTime: bigint;
        executed: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[_role: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resetUserPoints"
  ): TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sessionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "sessions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean, boolean] & {
        id: bigint;
        mentor: string;
        mentee: string;
        topic: string;
        duration: bigint;
        timestamp: bigint;
        verified: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "userBadges"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "users"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        role: bigint;
        contributionPoints: bigint;
        sessionsCompleted: bigint;
        sessionsVerified: bigint;
        registered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifySession"
  ): TypedContractMethod<[_sessionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [_proposalId: BigNumberish, _support: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BadgeAwarded"
  ): TypedContractEvent<
    BadgeAwardedEvent.InputTuple,
    BadgeAwardedEvent.OutputTuple,
    BadgeAwardedEvent.OutputObject
  >;
  getEvent(
    key: "PointsUpdated"
  ): TypedContractEvent<
    PointsUpdatedEvent.InputTuple,
    PointsUpdatedEvent.OutputTuple,
    PointsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SessionLogged"
  ): TypedContractEvent<
    SessionLoggedEvent.InputTuple,
    SessionLoggedEvent.OutputTuple,
    SessionLoggedEvent.OutputObject
  >;
  getEvent(
    key: "SessionVerified"
  ): TypedContractEvent<
    SessionVerifiedEvent.InputTuple,
    SessionVerifiedEvent.OutputTuple,
    SessionVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "BadgeAwarded(address,uint256)": TypedContractEvent<
      BadgeAwardedEvent.InputTuple,
      BadgeAwardedEvent.OutputTuple,
      BadgeAwardedEvent.OutputObject
    >;
    BadgeAwarded: TypedContractEvent<
      BadgeAwardedEvent.InputTuple,
      BadgeAwardedEvent.OutputTuple,
      BadgeAwardedEvent.OutputObject
    >;

    "PointsUpdated(address,uint256)": TypedContractEvent<
      PointsUpdatedEvent.InputTuple,
      PointsUpdatedEvent.OutputTuple,
      PointsUpdatedEvent.OutputObject
    >;
    PointsUpdated: TypedContractEvent<
      PointsUpdatedEvent.InputTuple,
      PointsUpdatedEvent.OutputTuple,
      PointsUpdatedEvent.OutputObject
    >;

    "ProposalCreated(uint256,address,string)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "SessionLogged(uint256,address,address,string)": TypedContractEvent<
      SessionLoggedEvent.InputTuple,
      SessionLoggedEvent.OutputTuple,
      SessionLoggedEvent.OutputObject
    >;
    SessionLogged: TypedContractEvent<
      SessionLoggedEvent.InputTuple,
      SessionLoggedEvent.OutputTuple,
      SessionLoggedEvent.OutputObject
    >;

    "SessionVerified(uint256,address)": TypedContractEvent<
      SessionVerifiedEvent.InputTuple,
      SessionVerifiedEvent.OutputTuple,
      SessionVerifiedEvent.OutputObject
    >;
    SessionVerified: TypedContractEvent<
      SessionVerifiedEvent.InputTuple,
      SessionVerifiedEvent.OutputTuple,
      SessionVerifiedEvent.OutputObject
    >;

    "UserRegistered(address,uint8)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;

    "VoteCast(uint256,address,bool,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
